<?php
/**
 * @category   Tcz
 * @package    Tcz_Enquiry
 * @author     kumarupadhyayaditya59@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tcz\Enquiry\Block;

use Magento\Framework\View\Element\Template\Context;
use Tcz\Enquiry\Model\EnquiryFactory;
/**
 * Enquiry List block
 */
class EnquiryListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Enquiry
     */
    protected $_enquiry;
    public function __construct(
        Context $context,
        EnquiryFactory $enquiry
    ) {
        $this->_enquiry = $enquiry;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Tcz Enquiry Module List Page'));
        
        if ($this->getEnquiryCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'tcz.enquiry.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getEnquiryCollection()
            );
            $this->setChild('pager', $pager);
            $this->getEnquiryCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getEnquiryCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $enquiry = $this->_enquiry->create();
        $collection = $enquiry->getCollection();
        $collection->addFieldToFilter('status','1');
        //$enquiry->setOrder('enquiry_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}