<?php
/**
 * @category   Tcz
 * @package    Tcz_Enquiry
 * @author     kumarupadhyayaditya59@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tcz\Enquiry\Block;

use Magento\Framework\View\Element\Template\Context;
use Tcz\Enquiry\Model\EnquiryFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Enquiry View block
 */
class EnquiryView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Enquiry
     */
    protected $_enquiry;
    public function __construct(
        Context $context,
        EnquiryFactory $enquiry,
        FilterProvider $filterProvider
    ) {
        $this->_enquiry = $enquiry;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Tcz Enquiry Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $enquiry = $this->_enquiry->create();
        $singleData = $enquiry->load($id);
        if($singleData->getEnquiryId() || $singleData['enquiry_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}